### ISSUE TITLE
Changing the environment

### ISSUE THREAD

**Issue by Swader** [simulatrex/simulatrex-engine#6]
I am experimenting with this for a bigger project and with Assistants API and long term memory, I am wondering about outputs alternative to "thought" that would be "action". Instead of just thinking about what to do, agents should be able to modify another agent - the environment. The environment itself should not have memory of changes, only latest state, but agents who affected it, and those who witnessed these changes should have memory of this.

Happy to help with a PR if you would be open to this modification, once I sufficiently absorb how this all works.

**Comment by Swader** [comment]
Awesome, I will try and hack my way around it then 👍 Need those NPCs to stop THINKING about this hostage situation and start DOING :)

**Comment by d42me** [comment]
Great, looking forward to the results. Let me know if you have questions and make sure to join our [discord](https://discord.gg/RjG64szFDR).

**Comment by d42me** [comment]
@Swader Update on this?

**Comment by Swader** [comment]
Got overwhelmed, sorry. Will get on it asap
